# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c276e7dbeab679d8be4b15bc28f5fc35b31297fecda7bdff38e38ec3de61ceedcdcc76510871e9af563f4443f8bd84b1fb2f092a4f0bf69e37e2d6e34b3602f5

test:
  secret_key_base: a9b8b7b63a41a4d4e3d27af515006b5186c212417def02460cce1677aebcdb4460b793fc1fdf04e9961ca2343c5c365bcda5fff7e71ea412991e279124df0a22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
